#+TITILE: My lily58 Configurations

* DONE Normal Layout
  CLOSED: [2020-04-18 Sat 16:38]

The normal minimum setup for a keyboard has around 60 keys. Taking HHKB as an example, it has 61 keys while lily58 has 57 (one as encoder). I rarely use CAPLOCKS so I just need to find 4 more keys to lose(lily58 has 1 more fn).
- I will move shift to thumb row so no need for 2 shifts.
- I can also use only 1 mod(super) key.
- Some hard to reach signs (=-= and =+= are moved to next layer). Note: need to re-visit choice of keys

The layout is generated by a modified version of [[http://mkweb.bcgsc.ca/carpalx/?][Carpalx]] with a rated effort of 1.6 or around 40% less than QWERTY.

I've enabled full key swaps except the pinky key for right home row and upper row (=[{= and =]}=)

The refined layout for the keyboard is listed below
#+begin_src
4                         `
5 / x b u f |   y l c g q [
6 m h o a i |   r n t s d ]
7 ' ; v j , | 1 . k w p z 6
    3 2 e 1 | 2 3 4 5

Left:
1 -> BackSpace
2 -> Riser
3 -> Mod (Super)
4 -> Esc
5 -> Tab
6 -> Ctrl
7 -> Alt

Right:
1 -> Enter
2 -> Space
3 -> Shift
4 -> Lower
5 -> Mod (Super) ?
6 -> Alt
#+end_src
* TODO Lower Layout
#+begin_src
e         /               6
f . 7 8 9 + |   \ _ / ,   7
g = 4 5 6 - |   { ( ) }   8
h 0 1 2 3 * | 1 < [ ] > - 9
    d c b a | 2 3 4 5
#+end_src

* DONE Riser Layout
  CLOSED: [2020-04-12 Sun 12:57]
The riser layout is quite simple. I'm just mapping the up/down/left/right arrows to the =hjkl= keys on the normal QWERTY keyboard.

* TODO Other optimizations  [1/5]
- [X] [[https://beta.docs.qmk.fm/using-qmk/advanced-keycodes/feature_space_cadet][Space Cadet Shift - QMK]]
Initially I thought the making the left/right shift as open/close parenthesis but shift keys are actually pretty far to reach and may be too much work on the pinky fingers. To me having them located somewhere convinient on lower layer is better.
- [ ] Encorders: Haven't figured out which keys to assign
- [ ] [[https://docs.qmk.fm/#/feature_oled_driver][OLED driver]]: Maybe?
- [ ] Tap Dancing:
On the second thought tap dancing is more useful than the space cadet shift. Since I'm going to map the number keys on the lower layer, all the symbols can be mapped to the same key. With tap dancing, the usage of lower key + shift can be avoided.
- [ ] Move shift key to thumb row with Sticky key
