#+TITILE: My lily58 Configurations
#+REVISION: ver 1

* DONE Normal Layout
  CLOSED: [2020-04-18 Sat 16:38]
The base layout will be colmak DH mod. However some certain changes are needed for mod keys.

The normal minimum setup for a keyboard has around 60 keys. Taking HHKB as an example, it has 61 keys while lily58 has 57 (one as encoder). I rarely use CAPLOCKS so I just need to find 4 more keys to lose(lily58 has 1 more fn).
- I will move shift to thumb row so no need for 2 shifts.
- I can also use only 1 mod(super) key.
- Some hard to reach signs (=-= and =+= are moved to next layer)

* DONE Lower Layout
  CLOSED: [2020-05-14 Thu 23:22]
#+begin_src
e                         6
f . 7 8 9 + |   \ _ / ,   7
g = 4 5 6 - |   { ( ) }   8
h 0 1 2 3 * | 1 < [ ] > ? 9
    d c b a | 2 3 4 5
#+end_src

Left: Will be the same as Normal Layout

Right:
6 -> F11
7 -> F12
8 -> F13
Others remain the same as Normal Layout


* DONE Riser Layout
  CLOSED: [2020-04-12 Sun 12:57]
The riser layout is quite simple. I'm just mapping the up/down/left/right arrows to the =hjkl= keys on the normal QWERTY keyboard.

* TODO Other optimizations  [4/5]
- [X] [[https://beta.docs.qmk.fm/using-qmk/advanced-keycodes/feature_space_cadet][Space Cadet Shift - QMK]]
Initially I thought the making the left/right shift as open/close parenthesis but shift keys are actually pretty far to reach and may be too much work on the pinky fingers. To me having them located somewhere convinient on lower layer is better.
- [X] Encorders: Haven't figured out which keys to assign
- [X] [[https://docs.qmk.fm/#/feature_oled_driver][OLED driver]]: Maybe?
- [X] Tap Dancing:
On the second thought tap dancing is more useful than the space cadet shift. Since I'm going to map the number keys on the lower layer, all the symbols can be mapped to the same key. With tap dancing, the usage of lower key + shift can be avoided.
- [ ] Move shift key to thumb row with Sticky key
