#+TITILE: My lily58 Configurations

* TODO Normal Layout
The layout is generated by a modified version of [[https://github.com/xsznix/keygen][xsznix/keygen]]. Lily58 has fewer keys than the Ergodox which the program was written for.

The refined layout for the keyboard is listed below
#+begin_src
4                         6
5 z w d p j |   q m u , / 7
6 r s t h n |   y i a o l 8
7 ' k g f b | 1 x v . ; - 9
    3 2 e 1 | 2 3 4 5

Left:
1 -> Enter
2 -> Riser
3 -> Mod (Super)
4 -> Esc
5 -> Tab
6 -> Ctrl
7 -> Alt

Right:
1 -> ??
2 -> Space
3 -> Shift
4 -> Lower
5 -> Mod (Super) ?
6 -> ??
7 -> ??
8 -> ??
9 -> Alt
#+end_src
* TODO Lower Layout
#+begin_src
e         /               6
f . 7 8 9 + |   \ _ = /   7
g = 4 5 6 - |   { ( ) } l 8
h 0 1 2 3 * | 1 < [ ] > - 9
    d c b a | 2 3 4 5
#+end_src

* DONE Riser Layout
  CLOSED: [2020-04-12 Sun 12:57]
The riser layout is quite simple. I'm just mapping the up/down/left/right arrows to the =hjkl= keys on the normal QWERTY keyboard.

* TODO Other optimizations  [1/5]
- [X] [[https://beta.docs.qmk.fm/using-qmk/advanced-keycodes/feature_space_cadet][Space Cadet Shift - QMK]]
Initially I thought the making the left/right shift as open/close parenthesis but shift keys are actually pretty far to reach and may be too much work on the pinky fingers. To me having them located somewhere convinient on lower layer is better.
- [ ] Encorders: Haven't figured out which keys to assign
- [ ] [[https://docs.qmk.fm/#/feature_oled_driver][OLED driver]]: Maybe?
- [ ] Tap Dancing:
On the second thought tap dancing is more useful than the space cadet shift. Since I'm going to map the number keys on the lower layer, all the symbols can be mapped to the same key. With tap dancing, the usage of lower key + shift can be avoided.
- [ ] Move shift key to thumb row with Sticky key
